name: Deploy Gradio App to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  workflow_dispatch:  # Allow manual triggering of the workflow

permissions:
  contents: write

jobs:
  deploy-gradio:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Deploy Gradio app dynamically
      - name: Deploy Gradio App
        env:
          API_KEY_1: ${{ secrets.OPENAI_API_KEY }}
          API_KEY_2: ${{ TAVILY_API_KEY }}
        run: |
          git config --global user.email "akileshjayakumar88@gmail.com"
          git config --global user.name "Akilesh Jayakumar"
          python agent/app.py --server-name 0.0.0.0 --server-port 8000
