name: Deploy Gradio App to Azure from Docker Hub

on:
  push:
    branches:
      - main # Trigger workflow on main branch updates
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 3: Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gradio-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/gradio-app:latest

      # Step 4: Deploy Docker Image to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          images: ${{ secrets.DOCKER_USERNAME }}/gradio-app:latest
          container-username: ${{ secrets.DOCKER_USERNAME }}
          container-password: ${{ secrets.DOCKER_PASSWORD }}
