name: Deploy Gradio App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on main branch updates
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gradio

      # Step 4: Export static files
      - name: Build Gradio static site
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: |
          python agent/app.py --export-static-files
          mv agent/exported_files/* .  # Move static files to the root for Pages to serve

      # Step 5: Commit changes to main
      - name: Commit and push changes
        run: |
          git config --global user.email "akileshjayakumar88@gmail.com"
          git config --global user.name "Akilesh Jayakumar"
          git add -A
          git commit -m "Update static site $(date +'%Y-%m-%d')"
          git push
