name: Deploy Gradio App to Azure from Docker Hub

on:
  push:
    branches:
      - main  # Trigger deployment on changes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Fetch only the latest commit for efficiency

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: . # Set build context to the root of the repository
          file: infra/Dockerfile # Use the Dockerfile from the 'infra' folder
          push: true # Push the built image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/gradio-app:latest

      # Step 5: Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 6: Create App Service if it doesn't exist
      - name: Create App Service if Missing
        run: |
          az group create --name <your-resource-group> --location <your-region>
          az appservice plan create --name <your-app-service-plan> --resource-group <your-resource-group> --sku B1 --is-linux
          az webapp show --name ${{ secrets.AZURE_APP_NAME }} --resource-group <your-resource-group> || \
          az webapp create --resource-group <your-resource-group> --plan <your-app-service-plan> \
            --name ${{ secrets.AZURE_APP_NAME }} \
            --runtime "DOCKER|latest" \
            --deployment-container-image-name ${{ secrets.DOCKER_USERNAME }}/gradio-app:latest
        env:
          AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}

      # Step 7: Deploy Docker Image to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME }}
          images: ${{ secrets.DOCKER_USERNAME }}/gradio-app:latest
