name: Deploy Gradio App with Docker

on:
  push:
    branches:
      - main # Trigger workflow on main branch updates
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Step 2: Build and Run Docker
      - name: Build Docker Image
        run: |
          docker build -t gradio-app -f infra/Dockerfile .

      - name: Run Docker Container
        run: |
          docker run -d -p 7860:7860 gradio-app

      # Step 3: Install and Run ngrok
      - name: Install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list >/dev/null
          sudo apt update && sudo apt install ngrok
          nohup ngrok http 7860 > /dev/null 2>&1 & sleep 5

      - name: Get ngrok Public URL
        run: |
          curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
