name: Run Python script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install gradio huggingface_hub

    # Debug Step: Check if HF_TOKEN is set and print token length
    - name: Verify HF_TOKEN
      run: |
        echo "Token length: ${#HF_TOKEN}"
      env:
        HF_TOKEN: ${{ secrets.hf_token }}

    # Log in to Hugging Face non-interactively
    - name: Log in to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.hf_token }}
      run: |
        python -c 'from huggingface_hub import login; login(token="${HF_TOKEN}")'

    - name: Deploy to Spaces
      env:
        HF_TOKEN: ${{ secrets.hf_token }}
      run: yes "" | gradio deploy
